version: '3.9'

services:
  mongodb:
    container_name: mongo.db
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/var/lib/monogodb/data
    networks:
      - exam
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: tanlan
      MONGO_INITDB_ROOT_PASSWORD: admin1234
  
  postgres:
    container_name: postgres.db
    environment:
      - POSTGRES_USER=tanlan
      - POSTGRES_PASSWORD=admin1234
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - exam
  seq:
    container_name: seq
    ports:
      - "5341:80"
    networks:
      - exam
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=tanlan
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin1234
    restart: unless-stopped
    volumes:
      - seq_data:/var/lib/seq/data/