version: '3.9'

services:
  mongodb:
    image: mongo:latest
  
  postgres:
    image: postgres:15.3-bullseye
  
  seq:
    image: datalust/seq:latest

networks:
  exam:
    driver: bridge
volumes:
  mongo-data:
  postgres_data:
  seq_data:
